// Malaysian states and cities data
export const malaysiaStates = [
  "Johor",
  "Kedah",
  "Kelantan",
  "Kuala Lumpur",
  "Labuan",
  "Melaka",
  "Negeri Sembilan",
  "Pahang",
  "Penang",
  "Perak",
  "Perlis",
  "Putrajaya",
  "Sabah",
  "Sarawak",
  "Selangor",
  "Terengganu",
];

// Cities by state
export const malaysiaCities = {
  Johor: [
    "Johor Bahru",
    "Batu Pahat",
    "Muar",
    "Kluang",
    "Segamat",
    "Pontian",
    "Kulai",
    "Kota Tinggi",
    "Mersing",
    "Pasir Gudang",
  ],
  Kedah: [
    "Alor Setar",
    "Sungai Petani",
    "Kulim",
    "Langkawi",
    "Jitra",
    "Yan",
    "Kuala Kedah",
    "Pokok Sena",
    "Bandar Baharu",
    "Gurun",
  ],
  Kelantan: [
    "Kota Bharu",
    "Pasir Mas",
    "Tumpat",
    "Kuala Krai",
    "Tanah Merah",
    "Bachok",
    "Pasir Puteh",
    "Machang",
    "Gua Musang",
    "Jeli",
  ],
  "Kuala Lumpur": [
    "Kuala Lumpur",
    "Wangsa Maju",
    "Batu",
    "Kepong",
    "Titiwangsa",
    "Setiawangsa",
    "Bukit Bintang",
    "Cheras",
    "Bandar Tun Razak",
    "Lembah Pantai",
  ],
  Labuan: ["Victoria", "Labuan", "Rancha-Rancha", "Nagalang", "Tanjung Kubong"],
  Melaka: [
    "Melaka City",
    "Alor Gajah",
    "Jasin",
    "Masjid Tanah",
    "Merlimau",
    "Sungai Udang",
    "Ayer Keroh",
    "Bemban",
    "Durian Tunggal",
  ],
  "Negeri Sembilan": [
    "Seremban",
    "Port Dickson",
    "Nilai",
    "Bahau",
    "Tampin",
    "Kuala Pilah",
    "Rembau",
    "Gemas",
    "Jelebu",
    "Labu",
  ],
  Pahang: [
    "Kuantan",
    "Temerloh",
    "Bentong",
    "Jerantut",
    "Pekan",
    "Raub",
    "Mentakab",
    "Maran",
    "Cameron Highlands",
    "Rompin",
  ],
  Penang: [
    "George Town",
    "Butterworth",
    "Bukit Mertajam",
    "Nibong Tebal",
    "Balik Pulau",
    "Air Itam",
    "Bayan Lepas",
    "Tanjung Tokong",
    "Tanjung Bungah",
    "Gelugor",
  ],
  Perak: [
    "Ipoh",
    "Taiping",
    "Teluk Intan",
    "Sitiawan",
    "Batu Gajah",
    "Lumut",
    "Kampar",
    "Tapah",
    "Bidor",
    "Kuala Kangsar",
  ],
  Perlis: ["Kangar", "Arau", "Kuala Perlis", "Padang Besar", "Simpang Ampat"],
  Putrajaya: [
    "Putrajaya",
    "Precinct 1",
    "Precinct 2",
    "Precinct 3",
    "Precinct 4",
    "Precinct 5",
    "Precinct 6",
    "Precinct 7",
    "Precinct 8",
    "Precinct 9",
  ],
  Sabah: [
    "Kota Kinabalu",
    "Sandakan",
    "Tawau",
    "Lahad Datu",
    "Keningau",
    "Semporna",
    "Kudat",
    "Ranau",
    "Beaufort",
    "Kota Belud",
  ],
  Sarawak: [
    "Kuching",
    "Miri",
    "Sibu",
    "Bintulu",
    "Limbang",
    "Sarikei",
    "Sri Aman",
    "Kapit",
    "Samarahan",
    "Mukah",
  ],
  Selangor: [
    "Shah Alam",
    "Petaling Jaya",
    "Klang",
    "Subang Jaya",
    "Ampang",
    "Kajang",
    "Selayang",
    "Rawang",
    "Sepang",
    "Hulu Langat",
  ],
  Terengganu: [
    "Kuala Terengganu",
    "Kemaman",
    "Dungun",
    "Besut",
    "Marang",
    "Hulu Terengganu",
    "Setiu",
    "Kuala Nerus",
    "Kerteh",
    "Paka",
  ],
};
